version: '3.7'

services:

  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
    expose:
      - "3307"
    ports:
      - "3307:3306"
    networks:
      - default

networks: 
  default:
    driver: bridge